# -*- coding: utf-8 -*-
"""Data_Analysis_With_Pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eQDS89riJ2toTlgkcSmIQ1YZZHT8k3IZ
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("juhibhojani/house-price")

print("Path to dataset files:", path)

import numpy as np
import pandas as pd
import os

csv_path = os.path.join(path, "house_prices.csv")
df = pd.read_csv(csv_path)

"""### **A. Basic Dataset Inspection & Cleaning**"""

house_price=df.copy()
house_price.head()

house_price.sample(5)

house_price.info()

house_price.describe()

house_price.isnull()

house_price.isnull().sum()

house_price.count()

house_price.shape

house_price.size

house_price[['Dimensions', 'Plot Area']]

house_price.drop(['Dimensions', 'Plot Area'], axis=1, inplace=True)

house_price.columns

house_price.isnull().sum()

"""## **Handling Missing Values of Bathroom, Transaction, Status, Furnishing and Description**"""

house_price['Transaction'].mode()

house_price['Transaction'] = house_price['Transaction'].fillna(house_price['Transaction'].mode()[0])

house_price["Transaction"].isnull().sum()

(house_price['Bathroom'] == '2').sum()

house_price['Bathroom'].value_counts()

(house_price['Bathroom']).dtype

house_price['Bathroom'] = pd.to_numeric(house_price['Bathroom'], errors='coerce')

(house_price['Bathroom']).value_counts()

house_price['Bathroom'] = house_price['Bathroom'].fillna(house_price['Bathroom'].mode()[0])

house_price['Bathroom'].isnull().sum()

house_price["Status"].isnull().sum()

house_price["Status"].value_counts()

house_price["Status"].unique()

house_price['Status'] = house_price['Status'].fillna('Ready to Move')

house_price["Status"].isnull().sum()

(house_price['Furnishing']).value_counts()

(house_price['Furnishing']).isnull().sum()

house_price['Furnishing'].sample(10)

house_price['Furnishing'] = house_price['Furnishing'].fillna('Semi-Furnished')

house_price['Furnishing'].isnull().sum()

house_price['Description'].isnull().sum()

house_price['Description'].value_counts()

house_price['Description'] = house_price['Description'].fillna('Multistorey apartment is available for sale. It is a good location property. Please contact for more details.')

house_price['Description'].isnull().sum()

"""### **Removing Unnecessary Features**"""

#house_price = house_price.drop(['Title', 'Description', 'Status', 'facing', 'overlooking', 'Society', 'Ownership'], axis=1) #(Already Deleted)

house_price.columns

house_price.count()

house_price['Floor'].value_counts()

house_price['Floor'] = house_price['Floor'].fillna('2 out of 4')

house_price['Floor'].isnull().sum()

house_price.rename(columns={'Amount(in rupees)': 'Amount'}, inplace=True)

house_price.rename(columns={'Price (in rupees)': 'Price'}, inplace=True)

house_price['Price'].value_counts()

house_price['Price'] = house_price['Price'].fillna(house_price['Price'].mean())

house_price['Price'].isnull().sum()

house_price[['Carpet Area', 'Balcony', 'Car Parking', 'Super Area']]

house_price['Balcony'].value_counts()

house_price['Balcony'] = house_price['Balcony'].fillna(house_price['Balcony'].mode()[0])

house_price.isnull().sum()

"""## **Handling And Cleaning Carpet Area and Super Area**"""

house_price.rename(columns={'Carpet Area': 'Carpet Area (Sqft)'}, inplace=True)

house_price.rename(columns={'Super Area': 'Super Area (Sqft)'}, inplace=True)

house_price['Carpet Area (Sqft)'] = house_price['Carpet Area (Sqft)'].astype(str)

house_price['Carpet Area (Sqft)'] = house_price['Carpet Area (Sqft)'].str.replace(r'[^0-9.]', '', regex=True)

house_price['Carpet Area (Sqft)'] = pd.to_numeric(house_price['Carpet Area (Sqft)'], errors='coerce')

house_price['Carpet Area (Sqft)'] = house_price['Carpet Area (Sqft)'].fillna(house_price['Carpet Area (Sqft)'].mean())

house_price['Super Area (Sqft)'] = house_price['Super Area (Sqft)'].astype(str)

house_price['Super Area (Sqft)'] = house_price['Super Area (Sqft)'].str.replace(r'[^0-9.]', '', regex=True)

house_price['Super Area (Sqft)'] = pd.to_numeric(house_price['Super Area (Sqft)'], errors='coerce')

house_price['Super Area (Sqft)'] = house_price['Super Area (Sqft)'].fillna(house_price['Super Area (Sqft)'].mean())

house_price.isnull().sum()

house_price['Car Parking'].value_counts()

house_price['Car Parking'] = house_price['Car Parking'].astype(str)

house_price['Car Parking'] = house_price['Car Parking'].str.strip().str.rstrip(',')

house_price['Car Parking'].value_counts()

house_price['Car Parking'] = house_price['Car Parking'].fillna('1 Covered')

house_price.isnull().sum()

house_price['Amount'].value_counts()

# Ensure string
house_price['Amount'] = house_price['Amount'].astype(str)

# Extract number part
house_price['Amount_Number'] = house_price['Amount'].str.extract(r'([\d.]+)')[0].astype(float)

# Extract unit part
house_price['Amount_Unit'] = house_price['Amount'].str.extract(r'([a-zA-Z]+)')[0]

house_price['Amount_Unit'].value_counts()

house_price['Amount_Unit'] = house_price['Amount_Unit'].replace('Call', pd.NA)

house_price['Amount_Unit'].value_counts()

house_price['Amount_Number'].isnull().sum()

def convert_to_rupees(row):
    unit = str(row['Amount_Unit']).lower()  # make lowercase for consistency
    if unit in ['lac', 'lacs']:
        return row['Amount_Number'] * 100_000
    elif unit in ['cr', 'crore']:
        return row['Amount_Number'] * 10_000_000
    else:
        return row['Amount_Number']  # unknown or NaN unit
house_price['Amount_Number'] = house_price.apply(convert_to_rupees, axis=1)

house_price.columns

house_price.drop(['Price_Unit'], axis=1, inplace=True)

house_price.columns

house_price

house_price.isnull().sum()

house_price['Amount_Number'] = house_price['Amount_Number'].fillna(house_price['Amount_Number'].mean())

house_price.isnull().sum()

house_price.drop(['Amount_Unit'], axis=1, inplace=True)

house_price.isnull().sum()

house_price.drop(['Amount'], axis=1, inplace=True)

house_price.rename(columns={'Amount_Number': 'Amount'}, inplace=True)

house_price